---
- name: Pull SonarQube Docker image (using custom Python interpreter)
  docker_image:
    name: sonarqube:latest
    source: pull
  vars:
    ansible_python_interpreter: "{{ app_dir }}/python3/bin/python3"


- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:latest
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    env:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      # SONAR_JDBC_URL: "jdbc:postgresql://localhost:5432/{{ database_users[0].db }}"
      # SONAR_JDBC_USERNAME: "{{ database_users[0].name }}"
      # SONAR_JDBC_PASSWORD: "{{ database_users[0].password }}"
    volumes:
      - sonarqube_data:/opt/apps/sonarqube/data
      - sonarqube_extensions:/opt/apps/sonarqube/extensions
      - sonarqube_logs:/opt/apps/sonarqube/logs
  vars:
    ansible_python_interpreter: "{{ app_dir }}/python3/bin/python3"
