- name: Manage PostgreSQL users and databases
  block:
    - name: Create PostgreSQL database explicitly
      shell: |
        sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='{{ item.db }}'" | grep -q 1 || sudo -u postgres createdb -E UTF8 {{ item.db }}
      loop: "{{ database_users }}"

    - name: Create PostgreSQL user explicitly
      shell: |
        sudo -u postgres psql -c "CREATE USER {{ item.name }} WITH PASSWORD '{{ item.password }}';" || true
      loop: "{{ database_users }}"

    - name: Set PostgreSQL user schema search path
      shell: |
        sudo -u postgres psql -d {{ item.db }} -c "ALTER USER {{ item.name }} SET search_path TO {{ item.schema }};"
      loop: "{{ database_users }}"

    - name: Grant all privileges to PostgreSQL user
      shell: |
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ item.db }} TO {{ item.name }};"
      loop: "{{ database_users }}"